#### AI Usage Report

## AI Tools Used
I used a combination of AI tools to accelerate the development process for this project. My primary tools were **GitHub Copilot** for code completion and in-editor suggestions, **Cursor IDE** which provided an integrated AI-powered development environment, and **v0.dev** for generating initial UI components. For broader architectural planning and debugging complex issues, I also leveraged large language models like ChatGPT.

## Sample Prompts 
1.  "Generate a responsive Next.js component for a testimonial carousel using Framer Motion and Shadcn/ui. It should feature a customer photo, name, role, company, rating, and a brief quote. Include navigation buttons for scrolling."
2.  "Help me create a `useToast` hook and `Toaster` component based on Radix UI, similar to the one in the `react-hot-toast` library. The logic should manage a queue of toasts and handle dismissals."
3.  "Refactor this pricing calculator component in TypeScript to be more dynamic. Create an interface for the pricing tiers and ensure the slider inputs are properly typed and update the displayed price in real-time."

## AI vs Manual Work Split
- **AI-generated**: Approximately 40% of the codebase was initially generated with AI. This primarily included boilerplate code for components like `Dialog`, `Sheet`, `Select`, and `Slider`, as well as the initial structure for the `Homepage`, `BlogPage`, and various UI sections. The foundation of many animations was also suggested by AI.
- **Manual coding**: Around 60% of the work was manual. This involved integrating the AI-generated components into the overall design system, customizing their props and styles to fit the "ADmyBRAND" aesthetic, and writing complex logic, such as the pricing calculator's formulas and the custom `useToast` hook. I also manually created the content for the blog posts, testimonials, and FAQs.
- **Customization**: A significant portion of my time was spent customizing and refining AI outputs. For example, I adapted the base `Button` component to include Framer Motion animations and a custom background gradient. For the modals, I modified the base Radix UI components generated by AI to include the unique glassmorphism styling and custom form logic. The AI's suggestions served as a strong starting point, but manual refinement was crucial to achieve the project's specific UI/UX goals.
